"""adding a profile picture field for user table

Revision ID: 8a2e39135d8a
Revises: ab63382c83cc
Create Date: 2024-05-07 20:54:01.467243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2e39135d8a'
down_revision = 'ab63382c83cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilePic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profilePic')

    # ### end Alembic commands ###
