"""add cascade deletion

Revision ID: b296ca0b4680
Revises: 8f0f5e909322
Create Date: 2024-05-14 14:25:58.461416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b296ca0b4680'
down_revision = '8f0f5e909322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_constraint('option_question_fk', type_='foreignkey')
        batch_op.create_foreign_key('option_question_fk', 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('question_survey_fk', type_='foreignkey')
        batch_op.create_foreign_key('question_survey_fk', 'survey', ['survey_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_constraint('survey_user_fk', type_='foreignkey')
        batch_op.create_foreign_key('survey_user_fk', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('is_published')

    with op.batch_alter_table('user_answer', schema=None) as batch_op:
        batch_op.drop_constraint('useranswer_user_fk', type_='foreignkey')
        batch_op.drop_constraint('useranswer_option_fk', type_='foreignkey')
        batch_op.create_foreign_key('useranswer_user_fk', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('useranswer_option_fk', 'option', ['option_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answer', schema=None) as batch_op:
        batch_op.drop_constraint('useranswer_option_fk', type_='foreignkey')
        batch_op.drop_constraint('useranswer_user_fk', type_='foreignkey')
        batch_op.create_foreign_key('useranswer_user_fk', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('useranswer_option_fk', 'option', ['option_id'], ['id'])

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint('fk_user_survey', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_survey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('survey_user_fk', type_='foreignkey')
        batch_op.create_foreign_key('survey_user_fk', 'survey', ['survey_id'], ['id'])

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_constraint('option_question_fk', type_='foreignkey')
        batch_op.create_foreign_key('option_question_fk', 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###
