"""add point field for User table

Revision ID: ed28c232af03
Revises: b296ca0b4680
Create Date: 2024-05-15 19:15:22.342020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed28c232af03'
down_revision = 'b296ca0b4680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_username_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_username_uc', ['username'])
        batch_op.drop_column('point')

    # ### end Alembic commands ###
